### ISSUE TITLE
error using ClustAGE

### ISSUE THREAD

**Issue by sekhwal** [egonozer/Spine#2]
Hi, I am trying to run perl subelements_to_tree.pl in ClustAGE. However, it is showing following error.
----------
Can't locate File/Which.pm in @INC (you may need to install the File::Which module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at subelements_to_tree.pl line 23.
BEGIN failed--compilation aborted at subelements_to_tree.pl line 23.

**Comment by egonozer** [comment]
Fixed this issue in v0.2.4
